-- Fixtures schema for team-specific non-net bookings.
-- Run this in Supabase SQL Editor.

create table if not exists public.fixtures (
    id bigint generated by default as identity primary key,
    team_key text not null check (team_key in ('plucky', 'unabombers')),
    title text,
    opponent text,
    start_at timestamptz not null,
    end_at timestamptz not null,
    capacity integer not null check (capacity > 0),
    location text,
    notes text,
    locked boolean not null default false,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.fixture_bookings (
    id bigint generated by default as identity primary key,
    fixture_id bigint not null references public.fixtures (id) on delete cascade,
    email text not null,
    status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
    created_at timestamptz not null default timezone('utc', now()),
    cancelled_at timestamptz
);

create unique index if not exists fixture_bookings_confirmed_unique
    on public.fixture_bookings (fixture_id, email)
    where status = 'confirmed';

create index if not exists fixture_bookings_fixture_status_idx
    on public.fixture_bookings (fixture_id, status);

create or replace view public.fixture_availability as
select
    f.id,
    f.team_key,
    f.title,
    f.opponent,
    f.start_at,
    f.end_at,
    f.capacity,
    f.location,
    f.notes,
    f.locked,
    f.created_at,
    count(b.id) filter (where b.status = 'confirmed')::int as confirmed_count,
    greatest(
        f.capacity - count(b.id) filter (where b.status = 'confirmed'),
        0
    )::int as slots_remaining
from public.fixtures as f
left join public.fixture_bookings as b
    on b.fixture_id = f.id
group by f.id;

create or replace function public.book_fixture_email(
    p_fixture_id bigint,
    p_email text
) returns void
language plpgsql
security definer
as $$
declare
    v_capacity integer;
    v_confirmed_count integer;
    v_locked boolean;
begin
    p_email := lower(trim(p_email));
    if p_email is null or p_email = '' then
        raise exception 'email_required';
    end if;

    if not exists (
        select 1
        from public.allowed_emails
        where email = p_email
    ) then
        raise exception 'email_not_allowed';
    end if;

    select capacity, locked
    into v_capacity, v_locked
    from public.fixtures
    where id = p_fixture_id
    for update;

    if not found then
        raise exception 'fixture_not_found';
    end if;

    if coalesce(v_locked, false) then
        raise exception 'fixture_locked';
    end if;

    if exists (
        select 1
        from public.fixture_bookings
        where fixture_id = p_fixture_id
          and email = p_email
          and status = 'confirmed'
    ) then
        raise exception 'already_booked';
    end if;

    select count(*)::int
    into v_confirmed_count
    from public.fixture_bookings
    where fixture_id = p_fixture_id
      and status = 'confirmed';

    if v_confirmed_count >= v_capacity then
        raise exception 'fixture_full';
    end if;

    insert into public.fixture_bookings (fixture_id, email, status)
    values (p_fixture_id, p_email, 'confirmed');
end;
$$;

grant execute on function public.book_fixture_email(bigint, text)
    to anon, authenticated, service_role;
